// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tapuwaprztdzsapsyevo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhcHV3YXByenRkenNhcHN5ZXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTM1MTMsImV4cCI6MjA2OTYyOTUxM30.eJjrjFkxSkhG1K_nSOvKq_LRsYVAMj9qW5cOYthmXQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});